export { default as Section } from '@/components/Section';
export { default as Services } from '@/components/Services';
export { default as Projects } from '@/components/Projects';
export { default as Testimonials } from '@/components/Testimonials';
export { default as HireMe } from '@/components/HireMe';
export { default as Navigation } from '@/components/Navigation';
export { default as NavButton } from '@/components/NavButton';
export { default as GoogleTagManager } from '@/components/GoogleTagManager';
export { default as Container } from '@/components/Container';
export { Sections } from '@/components/Sections';